Support caching of cloned repositories and add new 'versionformat' option.

diff --git a/tar_scm b/tar_scm
--- a/tar_scm
+++ b/tar_scm
@@ -10,103 +10,140 @@
 # of the License, or (at your option) any later version.  
 # See http://www.gnu.org/licenses/gpl-2.0.html for full license text.  
 
-# defaults
-MYSCM=""
-MYURL=""
-MYVERSION="_auto_"
-MYPREFIX=""
-MYFILENAME=""
-MYREVISION=""
-MYPACKAGEMETA=""
-MYGITARGS="--depth 1"
-INCLUDES=""
+SERVICE='tar_scm'
 
-while test $# -gt 0; do
-  case $1 in
-    *-scm)
-      MYSCM="$2"
-      shift
-    ;;
-    *-url)
-      MYURL="$2"
-      shift
-    ;;
-    *-subdir)
-      MYSUBDIR="$2"
-      shift
-    ;;
-    *-revision)
-      MYREVISION="$2"
-      shift
-    ;;
-    *-version)
-      MYVERSION="$2"
-      shift
-    ;;
-    *-include)
-      INCLUDES="$INCLUDES $2"
-      shift
-    ;;
-    *-versionprefix)
-      MYPREFIX="$2"
-      shift
-    ;;
-    *-exclude)
-      EXCLUDES="$EXCLUDES --exclude=${2#/}"
-      shift
-    ;;
-    *-filename)
-      MYFILENAME="${2#/}"
-      shift
-    ;;
-    *-package-meta)
-      MYPACKAGEMETA="${2#/}"
-      shift
-    ;;
-    *-outdir)
-      MYOUTDIR="$2"
-      shift
-    ;;
-    *-history-depth)
-      if [ "$2" == "full" ]; then
-        MYGITARGS="--depth 999999999"
-      else
-        MYGITARGS="--depth $2"
-      fi
-      shift
-    ;;
-    *)
-      echo Unknown parameter $1.
-      echo 'Usage: tar_scm --scm $SCM --url $URL --outdir $OUT'
-      exit 1
-    ;;
-  esac
-  shift
-done
+set_default_params () {
+  MYSCM=""
+  MYURL=""
+  MYVERSION="_auto_"
+  MYFORMAT=""
+  MYPREFIX=""
+  MYFILENAME=""
+  MYREVISION=""
+  MYPACKAGEMETA=""
+#  MYHISTORYDEPTH=""
+  INCLUDES=""
+}
 
-FILE="$MYFILENAME"
-VERSION="$MYVERSION"
-if [ -z "$MYPACKAGEMETA" ]; then
-  EXCLUDES="$EXCLUDES --exclude=.$MYSCM"
-fi
+get_config_options () {
+  # config options for this host ?
+  if [ -f /etc/obs/services/$SERVICE ]; then
+    . /etc/obs/services/$SERVICE
+  fi
+  # config options for this user ?
+  if [ -f "$HOME"/.obs/$SERVICE ]; then
+    . "$HOME"/.obs/$SERVICE
+  fi
+}
 
-if [ -z "$MYSCM" ]; then
-  echo "ERROR: no scm is given via --scm parameter (git/svn/hg/bzr)!"
+parse_params () {
+  while test $# -gt 0; do
+    case $1 in
+      *-scm)
+        MYSCM="$2"
+        shift
+      ;;
+      *-url)
+        MYURL="$2"
+        shift
+      ;;
+      *-subdir)
+        MYSUBDIR="$2"
+        shift
+      ;;
+      *-revision)
+        MYREVISION="$2"
+        shift
+      ;;
+      *-version)
+        MYVERSION="$2"
+        shift
+      ;;
+      *-include)
+        INCLUDES="$INCLUDES $2"
+        shift
+      ;;
+      *-versionformat)
+        MYFORMAT="$2"
+        shift
+      ;;
+      *-versionprefix)
+        MYPREFIX="$2"
+        shift
+      ;;
+      *-exclude)
+        EXCLUDES="$EXCLUDES --exclude=${2#/}"
+        shift
+      ;;
+      *-filename)
+        MYFILENAME="${2#/}"
+        shift
+      ;;
+      *-package-meta)
+        MYPACKAGEMETA="${2#/}"
+        shift
+      ;;
+      *-outdir)
+        MYOUTDIR="$2"
+        shift
+      ;;
+      *-history-depth)
+        echo "history-depth parameter is obsolete and will be ignored"
+        shift
+      ;;
+      *)
+        echo "Unknown parameter: $1"
+        echo 'Usage: $SERVICE --scm $SCM --url $URL [--subdir $SUBDIR] [--revision $REVISION] [--version $VERSION] [--include $INCLUDE]* [--exclude $EXCLUDE]* [--versionformat $FORMAT] [--versionprefix $PREFIX] [--filename $FILENAME] [--package-meta $META] --outdir $OUT'
+        exit 1
+      ;;
+    esac
+    shift
+  done
+}
+
+error () {
+  echo "ERROR: $*"
   exit 1
-fi
-if [ -z "$MYURL" ]; then
-  echo "ERROR: no checkout URL is given via --url parameter!"
-  exit 1
-fi
-if [ -z "$MYOUTDIR" ]; then
-  echo "ERROR: no output directory is given via --outdir parameter!"
-  exit 1
-fi
+}
 
-SRCDIR=$(pwd)
-cd "$MYOUTDIR"
+debug () {
+  [ -n "$DEBUG_TAR_SCM" ] && echo "$*"
+}
 
-if [ -z "$FILE" ]; then
+safe_run () {
+  if ! "$@"; then
+    error "$* failed; aborting!"
+  fi
+}
+
+sanitise_params () {
+  TAR_VERSION="$MYVERSION"
+
+  if [ -z "$MYSCM" ]; then
+    error "no scm is given via --scm parameter (git/svn/hg/bzr)!"
+  fi
+  if [ -z "$MYURL" ]; then
+    error "no checkout URL is given via --url parameter!"
+  fi
+  if [ -z "$MYOUTDIR" ]; then
+    error "no output directory is given via --outdir parameter!"
+  fi
+
+  FILE="$MYFILENAME"
+  WD_VERSION="$MYVERSION"
+  if [ -z "$MYPACKAGEMETA" ]; then
+    EXCLUDES="$EXCLUDES --exclude=.$MYSCM"
+  fi
+  # if [ "$MYHISTORYDEPTH" == "full" ]; then
+  #   MYHISTORYDEPTH="999999999"
+  # fi
+}
+
+detect_default_filename_param () {
+  if [ -n "$FILE" ]; then
+    return
+  fi
+
   case "$MYSCM" in
     git)
       FILE="${MYURL%/}"
@@ -118,187 +155,310 @@ if [ -z "$FILE" ]; then
       FILE="${MYURL%/}"
       FILE="${FILE##*/}"
       ;;
+    *)
+      error "unknown SCM '$MYSCM'"
   esac
-fi
+}
 
-# Try to find an existing tar ball, which can be upgraded instead of complete full download.
-existing_tar=$(echo $SRCDIR/.old/_service:*tar_scm:${FILE}-*.tar*)
-if [ ! -e "$existing_tar" ]; then
-  # for OBS < 2.3
-  existing_tar=$(echo $SRCDIR/_service:*tar_scm:${FILE}-*.tar*)
-fi
-if [ -e "$existing_tar" ]; then
-  UNCOMPRESS="cat"
-  if [ "${existing_tar%.tar.gz}" != "$existing_tar" ]; then
-    UNCOMPRESS="gunzip -c"
-  elif [ "${existing_tar%.tar.bz2}" != "$existing_tar" ]; then
-    UNCOMPRESS="bunzip2 -c"
-  elif [ "${existing_tar%.tar.xz}" != "$existing_tar" ]; then
-    UNCOMPRESS="xz -dc"
+fetch_upstream () {
+  TOHASH="$MYURL"
+  [ "$MYSCM" = 'svn' ] && TOHASH="$TOHASH/$MYSUBDIR"
+  HASH=`echo "$TOHASH" | sha256sum | cut -d\  -f 1`
+  REPOCACHE=
+  if [ -n "$CACHEDIRECTORY" ]; then
+    REPOCACHEINCOMING="$CACHEDIRECTORY/incoming"
+    REPOCACHEROOT="$CACHEDIRECTORY/repo"
+    REPOCACHE="$REPOCACHEROOT/$HASH"
+    REPOURLCACHE="$CACHEDIRECTORY/repourl/$HASH"
   fi
-  if $UNCOMPRESS "$existing_tar" | tar xf -; then
-    TAR_DIRECTORY=`find * -maxdepth 0 -a -type d`
-  else
-    existing_tar=""
-  fi
-else
-  existing_tar=""
-fi
 
-if [ "$MYSCM" == "svn" ]; then
-  if [[ $(svn --version --quiet) > "1.5.99" ]]; then
-    TRUST_SERVER_CERT="--trust-server-cert";
-  fi
-  if [ -z "$MYSUBDIR" -a -d "$TAR_DIRECTORY/.svn" ]; then
-    # update existing content for speed/bandwidth reasons
-    cd "$TAR_DIRECTORY"
-    OLDVERSION=`LC_ALL=C svn info | sed -n 's,^Last Changed Rev: \(.*\),\1,p'` || exit 1
+  if [ -z "$MYREVISION" ]; then
+    case "$MYSCM" in
+      git)
+        MYREVISION=master
+        ;;
+      hg)
+        MYREVISION=tip
+        ;;
+      # bzr)
+      #   MYREVISION=HEAD
+      #   ;;
+    esac
     if [ -n "$MYREVISION" ]; then
-      svn up -r"$MYREVISION" || exit 1
-    else
-      svn up || exit 1
+      debug "no revision specified; defaulting to $MYREVISION"
     fi
-    NEWVERSION=`LC_ALL=C svn info | sed -n 's,^Last Changed Rev: \(.*\),\1,p'` || exit 1
-    cd -
-    mv "$TAR_DIRECTORY" "${FILE}" || exit 1
+  fi
+
+  debug "check local cache if configured"
+  if [ -n "$CACHEDIRECTORY" -a -d "$REPOCACHE/.$MYSCM" ]; then
+    debug "cache hit: $REPOCACHE/.$MYSCM"
+    check_cache
+    update_cache
+    REPOPATH="$REPOCACHE"
   else
-    # new checkout
-    if [ -n "$MYSUBDIR" ]; then
-      # just checkout the subdir
-      mkdir -p "$FILE"
-      cd "$FILE"
-      if [ "$MYSUBDIR" != "${MYSUBDIR#/}" ]; then
-        echo "ERROR: Absolute paths not permitted for --subdir"
-        exit 1
+    if [ -n "$CACHEDIRECTORY" ]; then
+      debug "cache miss: $REPOCACHE/.$MYSCM"
+    else
+      debug "cache not enabled"
+    fi
+
+    calc_dir_to_clone_to
+    debug "new $MYSCM checkout to $CLONE_TO"
+    initial_clone
+
+    if [ -n "$CACHEDIRECTORY" ]; then
+      cache_repo
+      REPOPATH="$REPOCACHE"
+    else
+      REPOPATH="$MYOUTDIR/$FILE"
+    fi
+  fi
+
+  safe_run cd "$REPOPATH"
+  switch_to_revision
+  if [ "$TAR_VERSION" == "_auto_" -o -n "$MYFORMAT" ]; then
+    detect_version
+  fi
+}
+
+calc_dir_to_clone_to () {
+  if [ -n "$CACHEDIRECTORY" ]; then
+    safe_run cd "$REPOCACHEINCOMING"
+    debug mktemp -d "tmp.XXXXXXX"
+    CLONE_TO=`mktemp -d "tmp.XXXXXXX"`
+  else
+    CLONE_TO="$FILE"
+  fi
+}
+
+initial_clone () {
+  case "$MYSCM" in
+    git)
+      # Clone with full depth; so that the revision can be found if specified
+      safe_run git clone "$MYURL" "$CLONE_TO"
+      ;;
+    svn)
+      args=
+      [ -n "$MYREVISION" ] && args="-r$MYREVISION"
+      if [[ $(svn --version --quiet) > "1.5.99" ]]; then
+        TRUST_SERVER_CERT="--trust-server-cert"
       fi
-    fi
-    if [ -n "$MYREVISION" ]; then
-      svn co --non-interactive $TRUST_SERVER_CERT -r"$MYREVISION" "$MYURL/$MYSUBDIR" "${MYSUBDIR:-$FILE}" || exit 1
-    else
-      svn co --non-interactive $TRUST_SERVER_CERT "$MYURL/$MYSUBDIR" "${MYSUBDIR:-$FILE}" || exit 1
-    fi
-    if [ -n "$MYSUBDIR" ]; then
-      cd -
-    fi
-  fi
-  if [ "$VERSION" == "_auto_" ]; then
-    cd "$FILE/$MYSUBDIR"
-    [ -n "$MYPREFIX" ] && MYPREFIX="$MYPREFIX.rev"
-    VERSION="$MYPREFIX"`LC_ALL=C svn info | sed -n 's,^Last Changed Rev: \(.*\),\1,p'` || exit 1
-    cd -
-  fi
-elif [ "$MYSCM" == "git" ]; then
-  if [ -z "$MYSUBDIR" -a -d "$TAR_DIRECTORY/.git" ]; then
-    # update existing content for speed/bandwidth reasons
-    cd "$TAR_DIRECTORY"
-    OLDVERSION=`git show --pretty=format:%at  | head -n 1`
-    git pull $MYGITARGS || exit 1
-    if [ -n "$MYREVISION" ]; then
-      git checkout "$MYREVISION" || exit 1
-    fi
-    NEWVERSION=`git show --pretty=format:%at  | head -n 1`
-    cd -
-    mv "$TAR_DIRECTORY" "${FILE}" || exit 1
+      safe_run svn checkout --non-interactive $TRUST_SERVER_CERT \
+        $args "$MYURL/$MYSUBDIR" "$CLONE_TO"
+      MYSUBDIR= # repo root is subdir
+      ;;
+    hg)
+      safe_run hg clone "$MYURL" "$CLONE_TO"
+      ;;
+    bzr)
+      args=
+      [ -n "$MYREVISION" ] && args="-r $MYREVISION"
+      safe_run bzr checkout $args "$MYURL" "$CLONE_TO"
+      ;;
+    *)
+      error "unknown SCM '$MYSCM'"
+  esac
+}
+
+cache_repo () {
+  if [ -e "$REPOCACHE" ]; then
+    error "Somebody else beat us to populating the cache for $MYURL ($REPOCACHE)"
   else
-    # new checkout
-    if [ -n "$MYREVISION" ]; then
-      #Clone with full depth; so that the revision can be found
-      git clone "$MYURL" "${FILE}" || exit 1
-      cd "$FILE"
-      git checkout "$MYREVISION" || exit 1
-      cd -
-    else
-      #Clone only the latest revision
-      git clone --depth 1 "$MYURL" "${FILE}" || exit 1
-    fi
+    # FIXME: small race window here; do source services need to be thread-safe?
+    debug mv2 "$CLONE_TO" "$REPOCACHE"
+    safe_run mv "$CLONE_TO" "$REPOCACHE"
+    echo "$MYURL" > "$REPOURLCACHE"
+    echo "cached $MYURL at $REPOCACHE"
   fi
-  if [ "$VERSION" == "_auto_" ]; then
-    cd "$FILE"
-    [ -n "$MYPREFIX" ] && MYPREFIX="$MYPREFIX."
-    VERSION="$MYPREFIX"`git show --pretty=format:%at  | head -n 1`
-    cd -
+}
+
+check_cache () {
+  CACHEDURL=`cat "$REPOURLCACHE"`
+  [ -z "$CACHEDURL" ] && CACHEDURL='<unknown URL>'
+  if [ "$MYURL" != "$CACHEDURL" ]; then
+    error "Corrupt cache: cache for repo $MYURL was recorded as being from $CACHEDURL"
   fi
-elif [ "$MYSCM" == "hg" ]; then
-  if [ -z "$MYSUBDIR" -a -d "$TAR_DIRECTORY/.hg" ]; then
-    # update existing content for speed/bandwidth reasons
-    cd "$TAR_DIRECTORY"
-    OLDVERSION=`hg id -i -rtip`
-    hg pull || exit 1
-    NEWVERSION=`hg id -i -rtip`
-    cd -
-    mv "$TAR_DIRECTORY" "${FILE}" || exit 1
+}
+
+update_cache () {
+  safe_run cd "$REPOCACHE"
+
+  case "$MYSCM" in
+    git)
+      safe_run git fetch
+      ;;
+    svn)
+      args=
+      [ -n "$MYREVISION" ] && args="-r$MYREVISION"
+      safe_run svn update $args
+      MYSUBDIR= # repo root is subdir
+      ;;
+    hg)
+      if ! out=`hg pull`; then
+        if [[ "$out" == *'no changes found'* ]]; then
+          # Contrary to the docs, hg pull returns exit code 1 when
+          # there are no changes to pull, but we don't want to treat
+          # this as an error.
+          :
+        else
+          error "hg pull failed; aborting!"
+        fi
+      fi
+      ;;
+    bzr)
+      args=
+      [ -n "$MYREVISION" ] && args="-r$MYREVISION"
+      safe_run bzr update $args
+      ;;
+    *)
+      error "unknown SCM '$MYSCM'"
+  esac
+}
+
+switch_to_revision () {
+  case "$MYSCM" in
+    git)
+      safe_run git checkout "$MYREVISION"
+      if git branch | grep -q '^\* (no branch)$'; then
+        echo "$MYREVISION does not refer to a branch, not attempting git pull"
+      else
+        git pull
+      fi
+      ;;
+    svn|bzr)
+      : # should have already happened via checkout or update
+      ;;
+    hg)
+      safe_run hg update "$MYREVISION"
+      ;;
+    # bzr)
+    #   safe_run bzr update
+    #   if [ -n "$MYREVISION" ]; then
+    #     safe_run bzr revert -r "$MYREVISION"
+    #   fi
+    #   ;;
+    *)
+      error "unknown SCM '$MYSCM'"
+  esac
+}
+
+detect_version () {
+  if [ -z "$MYFORMAT" ]; then
+    case "$MYSCM" in
+      git)
+        MYFORMAT="%at"
+        ;;
+      hg)
+        MYFORMAT="{rev}"
+        ;;
+      svn|bzr)
+        MYFORMAT="%r"
+        ;;
+      *)
+        error "unknown SCM '$MYSCM'"
+        ;;
+    esac
+  fi
+
+  safe_run cd "$REPOPATH"
+  [ -n "$MYPREFIX" ] && MYPREFIX="$MYPREFIX."
+  get_version
+  TAR_VERSION="$MYPREFIX$version"
+}
+
+get_version () {
+  case "$MYSCM" in
+    git)
+      #version=`safe_run git show --pretty=format:"$MYFORMAT" | head -n 1`
+      version=`safe_run git log -n1 --pretty=format:"$MYFORMAT"`
+      ;;
+    svn)
+      #rev=`LC_ALL=C safe_run svn info | awk '/^Revision:/ { print $2 }'`
+      rev=`LC_ALL=C safe_run svn info | sed -n 's,^Last Changed Rev: \(.*\),\1,p'`
+      version="${MYFORMAT//%r/$rev}"
+      ;;
+    hg)
+      rev=`safe_run hg id -n`
+      version=`safe_run hg log -l1 -r$rev --template "$MYFORMAT"`
+      ;;
+    bzr)
+      #safe_run bzr log -l1 ...
+      rev=`safe_run bzr revno`
+      version="${MYFORMAT//%r/$rev}"
+      ;;
+    *)
+      error "unknown SCM '$MYSCM'"
+  esac
+}
+
+prep_tree_for_tar () {
+  if [ ! -e "$REPOPATH/$MYSUBDIR" ]; then
+    error "directory does not exist: $REPOPATH/$MYSUBDIR"
+  fi
+
+  if [ -z "$TAR_VERSION" ]; then
+    TAR_BASENAME="$FILE"
   else
-    # new checkout
-    hg clone "$MYURL" "${FILE}" || exit 1
+    TAR_BASENAME="${FILE}-${TAR_VERSION}"
   fi
-  if [ -n "$MYREVISION" ]; then
-    cd "$FILE"
-    hg update "$MYREVISION" || exit 1
-    cd -
+
+  MYINCLUDES=""
+
+  for INC in $INCLUDES; do
+    MYINCLUDES="$MYINCLUDES $TAR_BASENAME/$INC"
+  done
+  if [ -z "$MYINCLUDES" ]; then
+    MYINCLUDES="$TAR_BASENAME"
   fi
-  if [ "$VERSION" == "_auto_" ]; then
-    cd "$FILE"
-    [ -n "$MYPREFIX" ] && MYPREFIX="$MYPREFIX."
-    # current working revision
-    VERSION="$MYPREFIX"`hg id -n`
-    cd -
-  fi
-elif [ "$MYSCM" == "bzr" ]; then
-  if [ -z "$MYSUBDIR" -a -d "$TAR_DIRECTORY/.bzr" ]; then
-    # update existing content for speed/bandwidth reasons
-    cd "$TAR_DIRECTORY"
-    OLDVERSION=`bzr revno`
-    bzr update || exit 1
-    if [ -n "$MYREVISION" ]; then
-      bzr revert -r "$MYREVISION" || exit 1
-    fi
-    NEWVERSION=`bzr revno`
-    cd -
-    mv "$TAR_DIRECTORY" "${FILE}" || exit 1
+
+  safe_run cd "$MYOUTDIR"
+
+  if [ -n "$CACHEDIRECTORY" ]; then
+    debug cp -a "$REPOPATH/$MYSUBDIR" "$TAR_BASENAME"
+    safe_run cp -a "$REPOPATH/$MYSUBDIR" "$TAR_BASENAME"
   else
-    # new checkout
-    if [ -n "$MYREVISION" ]; then
-      bzr checkout -r "$MYREVISION" "$MYURL" "${FILE}" || exit 1
-    else
-      bzr checkout "$MYURL" "${FILE}" || exit 1
-    fi
+    debug mv3 "$REPOPATH/$MYSUBDIR" "$TAR_BASENAME"
+    safe_run mv "$REPOPATH/$MYSUBDIR" "$TAR_BASENAME"
   fi
-  if [ "$VERSION" == "_auto_" ]; then
-    cd "$FILE"
-    [ -n "$MYPREFIX" ] && MYPREFIX="$MYPREFIX."
-    VERSION="$MYPREFIX"`bzr revno`
-    cd -
+}
+
+create_tar () {
+  TARFILE="${TAR_BASENAME}.tar"
+  TARPATH="$MYOUTDIR/$TARFILE"
+  debug tar cf "$TARPATH" $EXCLUDES $MYINCLUDES
+  safe_run tar cf "$TARPATH" $EXCLUDES $MYINCLUDES
+  echo "Created $TARFILE"
+}
+
+cleanup () {
+  debug rm -rf "$TAR_BASENAME" "$FILE"
+  rm -rf "$TAR_BASENAME" "$FILE"
+}
+
+main () {
+  set_default_params
+  if [ -z "$DEBUG_TAR_SCM" ]; then
+    get_config_options
+  else
+    # We're in test-mode, so don't let any local site-wide
+    # or per-user config impact the test suite.
+    :
   fi
-else
-  echo "ERROR: unknown scm $MYSCM"
-  exit 1
-fi
+  parse_params "$@"
+  sanitise_params
 
-if [ ! -e "$FILE/$MYSUBDIR" ]; then
-  echo "Directory does not exist: $FILE/$MYSUBDIR"
-  exit 1
-fi
+  SRCDIR=$(pwd)
+  cd "$MYOUTDIR"
+  detect_default_filename_param
 
-if [ -z "$VERSION" ]; then
-  FILENAME="$FILE"
-else
-  FILENAME="${FILE}-${VERSION}"
-fi
+  fetch_upstream
 
-MYINCLUDES=""
+  prep_tree_for_tar
+  create_tar
 
-for INC in $INCLUDES; do
-  MYINCLUDES="$MYINCLUDES $FILENAME/$INC"
-done
-if [ -z "$MYINCLUDES" ]; then
-  MYINCLUDES="$FILENAME"
-fi
+  cleanup
+}
 
-if [ "$FILE" != "$FILENAME" ]; then
-  mv "$FILE/$MYSUBDIR" "${FILENAME}" || exit 1
-fi
-
-tar cf "$MYOUTDIR/${FILENAME}.tar" $EXCLUDES $MYINCLUDES || exit 1
-rm -rf "${FILENAME}" "$FILE"
+main "$@"
 
 exit 0
